--- # Docker 测试环境配置
spring.servlet.multipart.location: /bms/server/temp

spring.boot.admin.client:
  enabled: false

snail-job:
  enabled: false
  port: 28080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      p6spy: false
      primary: master
      strict: true
      datasource:
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://mysql:3306/bms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
          username: root
          password: root
      hikari:
        maxPoolSize: 20
        minIdle: 5
        connectionTimeout: 30000
        validationTimeout: 5000
        idleTimeout: 600000
        maxLifetime: 1800000
        keepaliveTime: 30000

spring.data:
  redis:
    host: redis
    port: 6379
    database: 0
    password: bms123
    timeout: 10s
    ssl.enabled: false

redisson:
  keyPrefix:
  threads: 4
  nettyThreads: 8
  singleServerConfig:
    clientName: bms
    connectionMinimumIdleSize: 8
    connectionPoolSize: 32
    idleConnectionTimeout: 10000
    timeout: 3000
    subscriptionConnectionPoolSize: 50

mail:
  enabled: false

sms:
  config-type: yaml
  restricted: true
  minute-max: 1
  account-max: 30
  blends: {}

justauth:
  address: http://localhost:18080
