<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.bms</groupId>
        <artifactId>bms-common</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>bms-common-sse</artifactId>

    <description>
        bms-common-sse 模块
    </description>

    <dependencies>
        <dependency>
            <groupId>com.bms</groupId>
            <artifactId>bms-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.bms</groupId>
            <artifactId>bms-common-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.bms</groupId>
            <artifactId>bms-common-satoken</artifactId>
        </dependency>
        <dependency>
            <groupId>com.bms</groupId>
            <artifactId>bms-common-json</artifactId>
        </dependency>
    </dependencies>
</project>
